# Generated by Django 4.1.7 on 2023-07-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
                ('fecha_hora_ins', models.DateTimeField()),
                ('institucion', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=254)),
            ],
        ),
    ]
